### ISSUE TITLE
How-to install the plugin?

### ISSUE THREAD

**Issue by Ti-webdev** [TrilliumIT/docker-zfs-plugin#1]
Hello. Thank you so much for this plugin.
Please add information about installation.

**Comment by clinta** [comment]
Thanks for the report. I added installation instructions and included a system service file for running this plugin. Please let me know if this is clear enough to get started.

https://github.com/TrilliumIT/docker-zfs-plugin#installation

**Comment by Ti-webdev** [comment]
Than you again. The instructions is helpful.
