### ISSUE TITLE
/run/docker/plugins/zfs.sock: connect: connection refused

### ISSUE THREAD

**Issue by mlan** [TrilliumIT/docker-zfs-plugin#10]
Hello I just upgraded docker on my Ubuntu 18.04 machine and I now get errors when working with the docker-zfs-plugin. It is be cause the docker-zfs-plugin does not start automatically when the machine is rebooted.

If i start docker-zfs-plugin manually every thing seems to work fine

`$ systemctl start docker-zfs-plugin.service`

I tried to do some basic debugging and i found that zfs-import-cache.service, which prevents docker-zfs-plugin.service from staring, has failed, see below

`$ systemctl status zfs-import-cache.service`
```
● zfs-import-cache.service - Import ZFS pools by cache file
   Loaded: loaded (/lib/systemd/system/zfs-import-cache.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
Condition: start condition failed at Thu 2019-07-25 11:32:48 CEST; 32min ago
           └─ ConditionPathExists=/etc/zfs/zpool.cache was not met
     Docs: man:zpool(8)
```

So, we see that the reason that zfs-import-cache.service fails is that I do not have a /etc/zfs/zpool.cache on my machine. Perhaps nowadays using a /etc/zfs/zpool.cache is not required? (My machine has been running fine for a good year without it). I have a simple zfs setup; only one singe root pool, which gets loaded by the kernel i would assume.

I also note that  zfs-mount.service have some dependecy on zfs-import-cache.service:

`$ systemctl list-dependencies zfs-mount.service`
```
zfs-mount.service
● ├─system.slice
● ├─zfs-load-module.service
● └─zfs-import.target
●   └─zfs-import-cache.service 
```

So perhaps one can remove the zfs-import-cache.service requirement in /etc/systemd/system/docker-zfs-plugin.service? If so my machine would start the docker-zfs-plugin.service despite there not beeing any 
/etc/zfs/zpool.cache, (which is not used on my machine)?

Below is the behavior when docker-zfs-plugin is not running.

Running the docker volume inspect command gives the following error, after what appears to be a 15s timeout has expired.

`$ docker volume inspect rpool/docker-volumes/srv_mail-db`

`Error response from daemon: get rpool/docker-volumes/srv_mail-db: error while checking if volume "rpool/docker-volumes/srv_mail-db" exists in driver "zfs": Post http://%2Frun%2Fdocker%2Fplugins%2Fzfs.sock/VolumeDriver.Get: dial unix /run/docker/plugins/zfs.sock: connect: connection refused `

The docker version is:
`$ docker version`
```
Client: Docker Engine - Community
 Version:           19.03.0
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        aeac949
 Built:             Wed Jul 17 18:15:07 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.0
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       aeac949
  Built:            Wed Jul 17 18:13:43 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by clinta** [comment]
Can you make sure the plugin is running?

`# systemctl status docker-zfs-plugin`

And check if you have any logs:

`# journalctl -e -u docker-zfs-plugin`

**Comment by clinta** [comment]
Can you make sure the plugin is running?

`# systemctl status docker-zfs-plugin`

And check if you have any logs:

`# journalctl -e -u docker-zfs-plugin`

**Comment by mlan** [comment]
hello Clint,

I did update the original post, after some debugging. And now i do suggest a "fix". what do you think?

Kind regards, Martin

**Comment by clinta** [comment]
I would recommend just fixing your cache file. You may be booting okay without it, but that may change if you ever add a second pool. Just run `zpool set cachefile=/etc/zfs/zpool.cache rpool` and those services should start up again.

**Comment by mlan** [comment]
Hello Clint.

I hear you.  

Just out of curiosity: It appears that some system would use zfs-import-scan.service to find pools whereas others would use zfs-import-cache.service. Was there a particular reason why zfs-import-cache.service (and not zfs-import-scan.service) is required by docker-zfs-plugin.service (in addition to the zfs-mount.service)? 

Many thanks for you help.

Kind regards, Martin

**Comment by mlan** [comment]
I think that this issue is relatively well understood so i suggest to close it.
