### ISSUE TITLE
Version missmatch between release and cli

### ISSUE THREAD

**Issue by girstenbrei** [TrilliumIT/docker-zfs-plugin#11]
The version set in the source code (main.go:13) always reports '1.0.0' while the release tag is 'v0.5'. This could be solved by releasing a version 1.0.1, applying tags and reporting version correctly (Releasing a v0.6 with correct reporting version would be inconsistent, someone may parse the output of --version and will then get a smaller version reported after an update).

Greets,
Chris

**Comment by clinta** [comment]
Thanks for the heads up. v1.0.1 is now released.
