### ISSUE TITLE
running with coreos

### ISSUE THREAD

**Issue by rostchri** [TrilliumIT/docker-zfs-plugin#3]
Does not seem to work with latest coreos

cat /etc/os-release  
<pre>
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1451.2.0
VERSION_ID=1451.2.0
BUILD_ID=2017-06-22-2207
PRETTY_NAME="Container Linux by CoreOS 1451.2.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
</pre>

I installed zfsonlinux on coreos before using https://github.com/varasys/corezfs. So zfs itself and docker using zfs is running fine so far: docker info
<pre>
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 10
Server Version: 17.05.0-ce
Storage Driver: zfs
 Zpool: error while getting pool information strconv.ParseUint: parsing "": invalid syntax
 Zpool Health: not available
 Parent Dataset: ssd/docker
 Space Used By Parent: 2173041152
 Space Available: 151947066368
 Parent Quota: no
 Compression: off
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: v0.13.2 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
 selinux
Kernel Version: 4.11.6-coreos-r1
Operating System: Container Linux by CoreOS 1451.2.0 (Ladybug)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.779GiB
Name: up2
ID: VPDR:YKN4:O3MV:2RKE:EIUU:TBVT:EPOU:EJ2Z:4W47:MDAI:EG4O:B5ZA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
</pre>

 docker version
<pre>
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.6
 Git commit:   89658be
 Built:        Thu Jun 22 21:55:46 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.6
 Git commit:   89658be
 Built:        Thu Jun 22 21:55:46 2017
 OS/Arch:      linux/amd64
 Experimental: false
</pre>

Because /usr is not directly writable with coreos I installed /usr/bin/docker-zfs-plugin by doing:
<pre>
mkdir -p /opt/overlayusrbin /opt/overlayusrbin.wd
cp docker-zfs-plugin /opt/overlayusrbin/
mount -o "lowerdir=/usr/bin,upperdir=/opt/overlayusrbin,workdir=/opt/overlayusrbin.wd" -t overlay overlay /usr/bin
</pre>

I created docker-zfs-plugin.service too but I got following "error" when this service is started or when I execute  the command manually: /usr/bin/docker-zfs-plugin --dataset-name ssd/docker-volumes
<pre>
DEBU[0000] Creating new ZfsDriver.                      
DEPRECATED Action signature.  Must be `cli.ActionFunc`.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See https://github.com/urfave/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature
</pre>
But a new zfs ssd/docker-volumes has been created after starting.

Executing: docker volume create -d zfs --name=testzfsdata2 I got the following error:
<pre>
Error response from daemon: create testzfsdata2: Error looking up volume plugin zfs: legacy plugin: plugin not found
</pre>

So what is wrong here? 
Or is this plugin not needed anymore because docker already has its own zfs storage-driver?

**Comment by travishegner** [comment]
Thanks @rostchri for the report.

We've only ever tested this driver on Ubuntu Server 16.04, and we have very little experience with CoreOS. I will build a quick VM to see if we can replicate and figure out the issue.

The point of this driver is to create and store data into actual docker *volumes* (fully intended for container persistent storage), and is completely separate from docker's own zfs storage driver, who's purpose is for storing ephemeral data into a container's writable layer, and storing/sharing each of the image layers you may have on your system.

**Comment by clinta** [comment]
Do you have a `zfs.sock` file in `/var/run/docker/plugins`?

**Comment by travishegner** [comment]
I just pushed a change to the latest master which should eliminate the deprecation warning from urfave/cli

**Comment by rostchri** [comment]
maybe a strace-output can help here..
I destroyed ssd/docker-volumes before and executed: 
<pre>
strace -f /usr/bin/docker-zfs-plugin --dataset-name ssd/docker-volumes 
</pre>
as root (see output here: https://pastebin.com/4Rk6v6tL)
After that the following zfs-filessystem was created (without mountpoint)
ssd/docker-volumes                                                                  24K   142G    24K  legacy
/usr/bin/docker-zfs-plugin itself terminates with message:
<pre>
DEPRECATED Action signature.  Must be `cli.ActionFunc`.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See https://github.com/urfave/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature
</pre> 
and exit-code 0

up2 docker # find /var/run/docker
<pre>
/var/run/docker
/var/run/docker/swarm
/var/run/docker/libnetwork
/var/run/docker/libnetwork/738d370e9acf8a65e2df6ef2c8e73c0b39fb8e984c16ce7b7f7cc990bc20e6b2.sock
/var/run/docker/libcontainerd
/var/run/docker/libcontainerd/event.ts
/var/run/docker/libcontainerd/4c5ddbff5243478895f98978ca00894a07e32230f616cbd387979c9a7f6fad32
/var/run/docker/libcontainerd/4c5ddbff5243478895f98978ca00894a07e32230f616cbd387979c9a7f6fad32/init-stderr
/var/run/docker/libcontainerd/4c5ddbff5243478895f98978ca00894a07e32230f616cbd387979c9a7f6fad32/init-stdout
/var/run/docker/libcontainerd/4c5ddbff5243478895f98978ca00894a07e32230f616cbd387979c9a7f6fad32/init-stdin
/var/run/docker/libcontainerd/4c5ddbff5243478895f98978ca00894a07e32230f616cbd387979c9a7f6fad32/config.json
/var/run/docker/libcontainerd/docker-containerd.sock
/var/run/docker/libcontainerd/containerd
/var/run/docker/libcontainerd/containerd/4c5ddbff5243478895f98978ca00894a07e32230f616cbd387979c9a7f6fad32
/var/run/docker/libcontainerd/containerd/4c5ddbff5243478895f98978ca00894a07e32230f616cbd387979c9a7f6fad32/init
/var/run/docker/libcontainerd/containerd/4c5ddbff5243478895f98978ca00894a07e32230f616cbd387979c9a7f6fad32/init/starttime
/var/run/docker/libcontainerd/containerd/4c5ddbff5243478895f98978ca00894a07e32230f616cbd387979c9a7f6fad32/init/pid
/var/run/docker/libcontainerd/containerd/4c5ddbff5243478895f98978ca00894a07e32230f616cbd387979c9a7f6fad32/init/log.json
/var/run/docker/libcontainerd/containerd/4c5ddbff5243478895f98978ca00894a07e32230f616cbd387979c9a7f6fad32/init/shim-log.json
/var/run/docker/libcontainerd/containerd/4c5ddbff5243478895f98978ca00894a07e32230f616cbd387979c9a7f6fad32/init/control
/var/run/docker/libcontainerd/containerd/4c5ddbff5243478895f98978ca00894a07e32230f616cbd387979c9a7f6fad32/init/exit
/var/run/docker/libcontainerd/containerd/4c5ddbff5243478895f98978ca00894a07e32230f616cbd387979c9a7f6fad32/init/process.json
/var/run/docker/libcontainerd/containerd/4c5ddbff5243478895f98978ca00894a07e32230f616cbd387979c9a7f6fad32/state.json
/var/run/docker/libcontainerd/containerd/events.log
/var/run/docker/plugins
/var/run/docker/plugins/4c5ddbff5243478895f98978ca00894a07e32230f616cbd387979c9a7f6fad32
/var/run/docker/plugins/4c5ddbff5243478895f98978ca00894a07e32230f616cbd387979c9a7f6fad32/sshfs.sock
</pre>

No zfs.sock
I made experiments with docker-volume-sshfs from https://github.com/vieux/docker-volume-sshfs which is running fine with coreos. The install-routine of docker-volume-sshfs running: docker plugin install vieux/sshfs is running fine at coreos too. 

How can I build a new docker-zfs-plugin with latest code-changes? I have no experiences with go...

**Comment by rostchri** [comment]
Tried out the following:
<pre>
docker run -it  google/golang /bin/bash
</pre>
<pre>
root@a37c2dab3eca:~# go get github.com/TrilliumIT/docker-zfs-plugin
# github.com/TrilliumIT/docker-zfs-plugin
/go/src/github.com/TrilliumIT/docker-zfs-plugin/main.go:49: cannot use "zfs" (type string) as type int in argument to h.Handler.ServeUnix
</pre>

**Comment by travishegner** [comment]
The `google/golang` image is deprecated, and is providing a pretty old version of Go. The official image is now simply `golang`.

When using `go get` it pulls the latest versions of all dependencies, whereas we are using a tool called `glide` to do pinned versioning of dependencies. In any case, I pushed another change to master which fixes the `ServeUnix` function signature as well. Try these steps to get a new binary:

```
docker run -it golang /bin/bash
go get github.com/Masterminds/glide
cd src
mkdir github.com/TrilliumIT
cd github.com/TrilliumIT
git clone https://github.com/TrilliumIT/docker-zfs-plugin.git
cd docker-zfs-plugin
glide install
go build .
```
This should leave you with a `docker-zfs-plugin` binary in your current directory, which you should be able to plop into your CoreOS image to run.

This binary runs as a daemon, and should always be running as long as you plan to manipulate zfs datasets as docker volumes. The docker daemon uses the `zfs.sock` file referenced earlier to communicate with this daemon, so also make sure that file is created on start, and exists as long as the plugin is running.

Please let us know how it works out.

**Comment by rostchri** [comment]
Thanks for your instructions. That worked :)
And the newest code-changes are working too. 
Now the daemon is starting fine and remains running.

<pre>
up2 docker-zfs-plugin # ./docker-zfs-plugin --dataset-name ssd/docker-volumes 
DEBU[0000] Creating new ZfsDriver.
</pre>

<pre>
up2 docker-zfs-plugin # ps -ef | grep  docker-zfs-plugin
root     13853 13774  0 21:07 pts/0    00:00:00 ./docker-zfs-plugin --dataset-name ssd/docker-volumes
</pre>

Creating volumes is working too:

<pre>
up2 docker-zfs-plugin # docker volume create -d zfs --name=testzfsdata2
DEBU[0049] Capabilites                                   Request="{ map[]}"
DEBU[0049] Get                                           Request="{testzfsdata2 map[]}"
DEBU[0049] Create                                        Request="{testzfsdata2 map[]}"
DEBU[0049] Path                                          Request="{testzfsdata2 map[]}"
DEBU[0049] Get                                           Request="{testzfsdata2 map[]}"
testzfsdata2
up2 docker-zfs-plugin # zfs list
NAME                                                                               USED  AVAIL  REFER  MOUNTPOINT
ssd                                                                               4.24G   140G    24K  legacy
ssd/coredata                                                                       824M   140G   324K  /home/core/data
ssd/coredata/cloud-systems                                                         823M   140G   823M  /home/core/data/cloud-systems
ssd/docker                                                                        3.43G   140G  36.6M  /var/lib/docker
ssd/docker-volumes                                                                  48K   140G    24K  legacy
ssd/docker-volumes/testzfsdata2                                                     24K   140G    24K  legacy
ssd/docker/01f6a3c7d22e76ccec9a2269e243e3ea60b915ed804ac3a81fcf8e6acf8f7953         86K   140G   144M  legacy
ssd/docker/044c532fcfa67ee71534ae671f31d47c35dac279126a79d7f82de644e2f42648       94.5K   140G   226M  legacy
</pre>

I will make more tests and will use the zfs-docker-volumes for some of my docker-images now.
Thanks for your work and your quick support :)

**Comment by travishegner** [comment]
Excellent! I'm glad it is working for you. I'll close this issue, please feel free to reach out if you have any more questions.

**Comment by travishegner** [comment]
We may have cobbled our automated build process... after we verify that it is working again, we will kick off a new release with the latest changes.

**Comment by rostchri** [comment]
Some notices for coreos here:

I'm using this service now:

<pre>
[Unit]
Description=zfs plugin
After=zfs-mount.service zfs-import-scan.service
Before=docker.service
Requires=zfs-mount.service zfs-import-scan.service
ConditionPathIsMountPoint=/var/lib/docker

[Service]
ExecStart=/usr/local/bin/docker-zfs-plugin --dataset-name ssd/docker/zfsvolumes

[Install]
WantedBy=docker.service
</pre>

I don't know why you used /var/lib/docker-volumes/zfs as condition? Because normally
(at first start without never used docker-zfs-plugin in any way) the condition can't never be met because there is no /var/lib/docker-volumes/zfs. What exactly is the intention or the purpose of that condition? 

I changed zfs-import-cache.service to zfs-import-scan.service, because it makes more sense in my environment. Coreos is more "stateless". So normally there is no zfs-cache-file at all.

I changed the dataset-name option to "ssd/docker/zfsvolumes" where ssd/docker is mounted to /var/lib/docker. For me it feels more comfortable running it in this way. I hope this doesn't interfere with
dockers internal zfs-handling?

Normally the system (before any  docker-zfs-plugin is started) looks like that:
<pre>
up2 # zfs list        
NAME                                                                               USED  AVAIL  REFER  MOUNTPOINT
ssd                                                                               4.24G   140G    24K  legacy
ssd/coredata                                                                       824M   140G   324K  /home/core/data
ssd/coredata/cloud-systems                                                         823M   140G   823M  /home/core/data/cloud-systems
ssd/docker                                                                        3.43G   140G  36.6M  /var/lib/docker
ssd/docker/01f6a3c7d22e76ccec9a2269e243e3ea60b915ed804ac3a81fcf8e6acf8f7953         86K   140G   144M  legacy

up2  # mount | grep docker
ssd/docker on /var/lib/docker type zfs (rw,seclabel,xattr,noacl)
ssd/docker on /var/lib/docker/plugins/4c5ddbff5243478895f98978ca00894a07e32230f616cbd387979c9a7f6fad32/propagated-mount type zfs (rw,seclabel,xattr,noacl)
ssd/docker on /var/lib/docker/plugins/4c5ddbff5243478895f98978ca00894a07e32230f616cbd387979c9a7f6fad32/rootfs/mnt/volumes type zfs (rw,seclabel,xattr,noacl)
ssd/docker on /var/lib/docker/zfs type zfs (rw,seclabel,xattr,noacl)
ssd/docker/a21b8eafd6be3780e069a40d307929e69e98844d26efe410649f72539727ed00 on /var/lib/docker/zfs/graph/a21b8eafd6be3780e069a40d307929e69e98844d26efe410649f72539727ed00 type zfs (rw,relatime,context="system_u:object_r:svirt_lxc_file_t:s0:c428,c739",xattr,noacl)
shm on /var/lib/docker/containers/a25495da0e118b3c0a3281c390dc7c576fd22b5f78304e0634c0d29195e02b55/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,context="system_u:object_r:svirt_lxc_file_t:s0:c428,c739",size=65536k)
nsfs on /run/docker/netns/f14e3a609ef3 type nsfs (rw)

</pre>

I'm using this snippet for enabling docker-zfs-plugin.service in cloud-config.yml file (special for coreos):
<pre>
  # enable docker-zfs-plugin.service which is in use for docker volumes
  - name: docker-zfs-plugin.service
    enable: true
</pre>

Doing it in this way (no start: true option) docker-zfs-plugin.service is automatically started if docker comes up in coreos which is on demand and not mandatory at systemboot.

And for completeness docker-zfs-plugin.service - file is lying in /usr/local/etc/systemd/system/docker-zfs-plugin.service (together with all other zfs-service-files (created at installation using https://github.com/varasys/corezfs) and symlinked manually by doing:
ln -s /usr/local/etc/systemd/system/docker-zfs-plugin.service /etc/systemd/system/

This is running fine for me now...

After creation of a testvolume via: "docker volume create -d zfs --name=testdata" I see:

<pre>
ssd/docker/zfsvolumes                                                               51K   140G  25.5K  /var/lib/docker/zfsvolumes
ssd/docker/zfsvolumes/testdata                                                    25.5K   140G  25.5K  /var/lib/docker/zfsvolumes/testdata
</pre>

Next I will try out some docker-images using that volumes ...

**Comment by clinta** [comment]
Most storage drivers by convention put their data in `/var/lib/docker-volumes` so we do as well with the zfs plugin.

I wouldn't advise storing your volume data in `/var/lib/docker` because this is where the docker daemon stores all of it's own data and I wouldn't be shocked if an uninstall or upgrade of docker made significant changes inside that directory that could end up clobbering the data in your volumes.

It is expected that you will manually create a dataset with a mountpoint of `/var/lib/docker-volumes/zfs` before running the service. The conditionismountpoint directive enforces that.
