### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by segator** [TrilliumIT/docker-zfs-plugin#5]
`go install

zfs/driver.go:33:33: undefined: volume.Request
zfs/driver.go:33:49: undefined: volume.Response
zfs/driver.go:50:31: undefined: volume.Request
zfs/driver.go:50:47: undefined: volume.Response
zfs/driver.go:72:30: undefined: volume.Request
zfs/driver.go:72:46: undefined: volume.Response
zfs/driver.go:89:33: undefined: volume.Request
zfs/driver.go:89:49: undefined: volume.Response
zfs/driver.go:106:31: undefined: volume.Request
zfs/driver.go:106:47: undefined: volume.Response
zfs/driver.go:106:31: too many errors
`

**Comment by travishegner** [comment]
I can't seem to reproduce these messages exactly. Can you provide more detail on your environment and how you got these messages? Reading the message, It appears that the dependency on `github.com/docker/go-plugin-helpers` is not met. We use glide for our dependency management, so make sure you have glide installed. It's also possible that you are trying to build from outside of a proper go environment/path.

Make sure you are in a proper go environment, and have glide installed. Then try again.
