### ISSUE TITLE
"CreatedAt" appers to be wrong 

### ISSUE THREAD

**Issue by mlan** [TrilliumIT/docker-zfs-plugin#7]
Many thanks for a great plugin! It works very well. I found a minor issue: "CreatedAt" appers to be wrong, for example example:

`docker volume inspect srv_file-data`
```
[
    {
        "CreatedAt": "0001-01-01T00:00:00Z",
        "Driver": "zfs",
        "Labels": {
            "com.docker.compose.project": "srv",
            "com.docker.compose.version": "1.22.0",
            "com.docker.compose.volume": "file-data"
        },
        "Mountpoint": "/var/lib/docker-volumes/srv_file-data",
        "Name": "srv_file-data",
        "Options": null,
        "Scope": "local"
    }
]
```

**Comment by travishegner** [comment]
Hi mlan, thanks for the report!

This driver was written before the `CreatedAt` field was part of the volume library. Luckily, zfs stores the created time in it's metadata, so this should be a relatively trivial thing to implement.

**Comment by travishegner** [comment]
So I've implemented this in our driver, but the version of docker we are running in production (17.05) is not returning the `CreatedAt` field. Looking at the docker version, we may have fallen behind after the rename.

**Comment by mlan** [comment]
Hello travishegner,

I tested the version v0.4.2 of the docker-zfs-plugin on a ubuntu 18.04 server with docker version 18.06.1-ce. Now the "CreatedAt" field does indeed hold some interesting data. :)

Unfortunately, there has been a change of behavior which might break the docker-compose use-case a little bit.

With version v0.4.2 I need to say:
`docker volume inspect rpool/docker-volumes/srv_file-data`
```
[
    {
        "CreatedAt": "2018-10-18T20:25:49+02:00",
        "Driver": "zfs",
        "Labels": null,
        "Mountpoint": "/var/lib/docker-volumes/srv_file-data",
        "Name": "rpool/docker-volumes/srv_file-data",
        "Options": null,
        "Scope": "local"
    }
]
```
If I try this
`docker volume create --driver zfs new_volume_name`
Docker throws an error and no volume is created:
`Error response from daemon: create new_volume_name: VolumeDriver.Create: Invalid dataset name: new_volume_name`
The volume names now need to be the full dataset path. I agree that knowing the zfs dataset path is very useful, but perhaps using it as the volume name might be problematic sometimes?

**Comment by mlan** [comment]
I now read the updated README.md, and I understand that the change is intentional. I tried to use the full dataset name in the docker-compose.yml file but such names appears not to be supported:
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
volumes value 'rpool/docker-volumes/new_volume_name' does not match any of the regexes: '^[a-zA-Z0-9._-]+$'
```

**Comment by travishegner** [comment]
Hi @mlan,
Quite a while ago, we re-factored the plugin to utilize fully qualified names, and allow us to utilize more than just one pool for our containers. Unfortunately, we inadvertently forgot to publish that change (to master) or cut a release for it.

> knowing the zfs dataset path is very useful

Indeed, this was necessary for us, as we utilize multiple ZFS pools on our nodes.

The 0.4.x line has that change included, and also has an option "--enable-legacy-names", which keeps the old behavior of using "short" names.

We've deprecated and removed that option on the master branch however. With the 0.4.2 version you have an option to start the driver in legacy name mode:

`docker-zfs-plugin --dataset-name rpool/docker-volumes --enable-legacy-names`

I'm guessing this will be suitable for docker compose. We don't use docker compose, so we were not aware of this limitation. Leave it to the docker developers to put a (seemingly) unnecessary limitation on the volume name, only from a single tool.

Do you know why docker compose has that limitation? Is there a technical reason or did they just feel that `/` wasn't an appropriate character (though it works for us everywhere we use it)? I'd rather not keep the legacy names option around, but the only way to avoid it is to have the docker compose tool add `/` to their allowed volume name characters.

**Comment by clinta** [comment]
It looks like you can work around this by specifying the path with the `/` as the name, and using an id without a slash as the key in the compose file.

See: https://docs.docker.com/compose/compose-file/compose-file-v2/#name

And https://github.com/docker/compose/issues/5719#issuecomment-368730991

Something like 
```yaml
volumes:
  new_volume:
    name: rpool/docker-volumes/new_volume_name
```

**Comment by mlan** [comment]
Hi travishegner,

Many thanks for the detailed explanation. I will use the --enable-legacy-names option.

I have no insight in the docker-compose development, so I do not claim to know why, but, when using docker compose files all service names and volume names there in are automatically prepended with the project name which defaults to the name of the current folder. 

@clinta you were to fast for me. I will give it a try

**Comment by mlan** [comment]
Hi Clint,

I made some quick testing and, of cause, yes, what you suggest works. 

I will update my docker-compose.yml files accordingly. If I find any issue with this approach I will let you know.

many thanks for excellent support! :)

/Martin
